In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("RSSCCoordTestSmall.csv")

# New Section

In [ ]:
df["Location Isolated"]

0                  Honduras
1                  Honduras
2                  Honduras
3                  Honduras
4                  Honduras
5                  Honduras
6                  Honduras
7                  Honduras
8                  Honduras
9                  Honduras
10    Queensland, Australia
Name: Location Isolated, dtype: object

In [ ]:
df["Location (Country or Territory)"]

0      Honduras
1      Honduras
2      Honduras
3      Honduras
4      Honduras
5      Honduras
6      Honduras
7      Honduras
8      Honduras
9      Honduras
10    Australia
Name: Location (Country or Territory), dtype: object

In [ ]:
for index, row in df.iterrows():
  print(row["Location Isolated"], row["Location (Country or Territory)"])

Honduras Honduras
Honduras Honduras
Honduras Honduras
Honduras Honduras
Honduras Honduras
Honduras Honduras
Honduras Honduras
Honduras Honduras
Honduras Honduras
Honduras Honduras
Queensland, Australia Australia

In [ ]:
import requests
import os
# Your Mapbox access token
access_token = "pk.eyJ1IjoiYmhyYW1pcmUiLCJhIjoiY2x4dGY0cnd5MWNiajJyb214aTd1azgzbCJ9._tyRBeLHArE_dxGA9BP5fA"
# The base URL for the Mapbox Geocoding API
base_url = 'https://api.mapbox.com/search/geocode/v6/forward?'

In [ ]:
data = [{'q': 'Svalbard', }]
for d in data:
    params = {
    'q': d.get('q'),
    'country': d.get('country'),
    'access_token': access_token
    }
    # Make the request
    response = requests.get(base_url, params=params)

    # Check if the request was successful
    if response.status_code == 200:
        # Parse the JSON response
        data = response.json()
        # print(data)
        # print(f"Georgia's coordinates are {data.get('features')[0].get('geometry').get('coordinates')}")
        # print(f"Georgia's place name is {data.get('features')[0].get('properties').get('full_address')}\n\n")
        print(f"{d.get('q')}'s coordinates are {data.get('features')[0].get('geometry').get('coordinates')}")
        print(f"{d.get('q')}'s place name is {data.get('features')[0].get('properties').get('full_address')}\n\n")
        print(f"{d.get('q')}'s country is {data.get('features')[0].get('properties').get('context').get('country').get('name')}\n")
    else:
        print(f"Error: {response.status_code}")

Svalbard's coordinates are [20.294606, 78.715404]
Svalbard's place name is Svalbard and Jan Mayen


Svalbard's country is Svalbard and Jan Mayen

In [ ]:
count = 0
for index, row in df.iterrows():
      if count > 30: #Ben-This integer represents the cap on the query limit. MapBox has a query limit of 100,000 queries for free each month. If testing function, set limit to low integer i.e. 10
        break
      params = {
      'q': row['Location Isolated'],
      'access_token': access_token
      }
      # Make the request
      response = requests.get(base_url, params=params)
      count += 1
      # Check if the request was successful
      if response.status_code == 200:
          # Parse the JSON response
          data = response.json()
          print(f"{row['Location Isolated']}'s coordinate are {data.get('features')[0].get('geometry').get('coordinates')}")
      else:
          print(f"Error: {response.status_code}")

Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Queensland, Australia's coordinate are [144.55039, -22.572791]

In [ ]:
data

{'type': 'FeatureCollection',
 'features': [{'type': 'Feature',
   'id': 'dXJuOm1ieHBsYzpBU1FP',
   'geometry': {'type': 'Point', 'coordinates': [144.55039, -22.572791]},
   'properties': {'mapbox_id': 'dXJuOm1ieHBsYzpBU1FP',
    'feature_type': 'region',
    'full_address': 'Queensland, Australia',
    'name': 'Queensland',
    'name_preferred': 'Queensland',
    'coordinates': {'longitude': 144.55039, 'latitude': -22.572791},
    'place_formatted': 'Australia',
    'bbox': [137.994233, -29.177703, 153.645811, -9.051592],
    'context': {'country': {'mapbox_id': 'dXJuOm1ieHBsYzpJZzQ',
      'name': 'Australia',
      'wikidata_id': 'Q408',
      'country_code': 'AU',
      'country_code_alpha_3': 'AUS'},
     'region': {'mapbox_id': 'dXJuOm1ieHBsYzpBU1FP',
      'name': 'Queensland',
      'wikidata_id': 'Q36074'}}}},
  {'type': 'Feature',
   'id': 'dXJuOm1ieGFkci1zdHI6YzMxYTg3ZWEtYWVmZC00N2ExLTk3ZmYtMDg2YWNjZGM3YjNi',
   'geometry': {'type': 'Point', 'coordinates': [153.431525, -28.0247]},
   'properties': {'mapbox_id': 'dXJuOm1ieGFkci1zdHI6YzMxYTg3ZWEtYWVmZC00N2ExLTk3ZmYtMDg2YWNjZGM3YjNi',
    'feature_type': 'street',
    'full_address': 'Australia Avenue, Broadbeach Queensland 4218, Australia',
    'name': 'Australia Avenue',
    'name_preferred': 'Australia Avenue',
    'coordinates': {'longitude': 153.431525, 'latitude': -28.0247},
    'place_formatted': 'Broadbeach Queensland 4218, Australia',
    'context': {'street': {'mapbox_id': 'dXJuOm1ieGFkci1zdHI6YzMxYTg3ZWEtYWVmZC00N2ExLTk3ZmYtMDg2YWNjZGM3YjNi',
      'name': 'Australia Avenue'},
     'postcode': {'mapbox_id': 'dXJuOm1ieHBsYzp1TzRP', 'name': '4218'},
     'locality': {'mapbox_id': 'dXJuOm1ieHBsYzpEM2tLRGc',
      'name': 'Broadbeach',
      'wikidata_id': 'Q4972031'},
     'place': {'mapbox_id': 'dXJuOm1ieHBsYzpuVWdP',
      'name': 'Gold Coast',
      'wikidata_id': 'Q140075'},
     'region': {'mapbox_id': 'dXJuOm1ieHBsYzpBU1FP',
      'name': 'Queensland',
      'wikidata_id': 'Q36074',
      'region_code': 'QLD',
      'region_code_full': 'AU-QLD'},
     'country': {'mapbox_id': 'dXJuOm1ieHBsYzpJZzQ',
      'name': 'Australia',
      'wikidata_id': 'Q408',
      'country_code': 'AU',
      'country_code_alpha_3': 'AUS'}}}},
  {'type': 'Feature',
   'id': 'address.5623586393476390',
   'geometry': {'type': 'Point', 'coordinates': [153.107928, -27.762438]},
   'properties': {'mapbox_id': 'address.5623586393476390',
    'feature_type': 'street',
    'full_address': 'Australia Boulevard, Logan Village Queensland 4207, Australia',
    'name': 'Australia Boulevard',
    'name_preferred': 'Australia Boulevard',
    'coordinates': {'longitude': 153.107928, 'latitude': -27.762438},
    'place_formatted': 'Logan Village Queensland 4207, Australia',
    'context': {'street': {'mapbox_id': 'address.5623586393476390',
      'name': 'Australia Boulevard'},
     'postcode': {'mapbox_id': 'dXJuOm1ieHBsYzp0NDRP', 'name': '4207'},
     'place': {'mapbox_id': 'dXJuOm1ieHBsYzo2Q2dP',
      'name': 'Logan Village',
      'wikidata_id': 'Q6667232'},
     'region': {'mapbox_id': 'dXJuOm1ieHBsYzpBU1FP',
      'name': 'Queensland',
      'wikidata_id': 'Q36074',
      'region_code': 'QLD',
      'region_code_full': 'AU-QLD'},
     'country': {'mapbox_id': 'dXJuOm1ieHBsYzpJZzQ',
      'name': 'Australia',
      'wikidata_id': 'Q408',
      'country_code': 'AU',
      'country_code_alpha_3': 'AUS'}}}},
  {'type': 'Feature',
   'id': 'dXJuOm1ieGFkci1zdHI6OGQyYzI0MjUtOGIzNC00ZmQyLWEyMTUtMmQzNGUyYzhjYjMy',
   'geometry': {'type': 'Point', 'coordinates': [153.096257, -27.207108]},
   'properties': {'mapbox_id': 'dXJuOm1ieGFkci1zdHI6OGQyYzI0MjUtOGIzNC00ZmQyLWEyMTUtMmQzNGUyYzhjYjMy',
    'feature_type': 'street',
    'full_address': 'Australia Court, Newport Queensland 4020, Australia',
    'name': 'Australia Court',
    'name_preferred': 'Australia Court',
    'coordinates': {'longitude': 153.096257, 'latitude': -27.207108},
    'place_formatted': 'Newport Queensland 4020, Australia',
    'context': {'street': {'mapbox_id': 'dXJuOm1ieGFkci1zdHI6OGQyYzI0MjUtOGIzNC00ZmQyLWEyMTUtMmQzNGUyYzhjYjMy',
      'name': 'Australia Court'},
     'postcode': {'mapbox_id': 'dXJuOm1ieHBsYzpyRTRP', 'name': '4020'},
     'locality': {'mapbox_id': 'dXJuOm1ieHBsYzpFQ3hLRGc',
      'name': 'Newport',
      'wikidata_id': 'Q7018710'},
     'place': {'mapbox_id': 'dXJuOm1ieHBsYzpPd2dP',
      'name': 'Brisbane',
      'wikidata_id': 'Q34932'},
     'region': {'mapbox_id': 'dXJuOm1ieHBsYzpBU1FP',
      'name': 'Queensland',
      'wikidata_id': 'Q36074',
      'region_code': 'QLD',
      'region_code_full': 'AU-QLD'},
     'country': {'mapbox_id': 'dXJuOm1ieHBsYzpJZzQ',
      'name': 'Australia',
      'wikidata_id': 'Q408',
      'country_code': 'AU',
      'country_code_alpha_3': 'AUS'}}}},
  {'type': 'Feature',
   'id': 'address.6287812270070560',
   'geometry': {'type': 'Point', 'coordinates': [152.901584, -27.673154]},
   'properties': {'mapbox_id': 'address.6287812270070560',
    'feature_type': 'street',
    'full_address': 'Australia Avenue, Brookwater Queensland 4300, Australia',
    'name': 'Australia Avenue',
    'name_preferred': 'Australia Avenue',
    'coordinates': {'longitude': 152.901584, 'latitude': -27.673154},
    'place_formatted': 'Brookwater Queensland 4300, Australia',
    'context': {'street': {'mapbox_id': 'address.6287812270070560',
      'name': 'Australia Avenue'},
     'postcode': {'mapbox_id': 'dXJuOm1ieHBsYzp1MjRP', 'name': '4300'},
     'locality': {'mapbox_id': 'dXJuOm1ieHBsYzpEM3FLRGc',
      'name': 'Brookwater',
      'wikidata_id': 'Q4975216'},
     'place': {'mapbox_id': 'dXJuOm1ieHBsYzpPd2dP',
      'name': 'Brisbane',
      'wikidata_id': 'Q34932'},
     'region': {'mapbox_id': 'dXJuOm1ieHBsYzpBU1FP',
      'name': 'Queensland',
      'wikidata_id': 'Q36074',
      'region_code': 'QLD',
      'region_code_full': 'AU-QLD'},
     'country': {'mapbox_id': 'dXJuOm1ieHBsYzpJZzQ',
      'name': 'Australia',
      'wikidata_id': 'Q408',
      'country_code': 'AU',
      'country_code_alpha_3': 'AUS'}}}}],
 'attribution': 'NOTICE: © 2024 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained.'}

In [ ]:
# Check the length of the features list before trying to access the second element
if len(data.get('features')) > 0:
    # If there's more than one feature, proceed
    print(type(data.get('features')[0].get('geometry').get('coordinates')[0]))
else:
    print("There's only one feature in the results.")

<class 'float'>

In [ ]:
count = 0
output_data = []
for index, row in df.iterrows():
      if count > 1:
        break
      params = {
      'q': row['Location Isolated'],
      'access_token': access_token
      }

      # Make the request
      response = requests.get(base_url, params=params)
      count += 1
      # Check if the request was successful
      if response.status_code == 200:
          # Parse the JSON response
          data = response.json()
          print(f"{row['Location Isolated']}'s coordinate are {data.get('features')[0].get('geometry').get('coordinates')}")
          return_data = {"Long": data.get('features')[0].get('geometry').get('coordinates')[0],
                         "Lat" : data.get('features')[0].get('geometry').get('coordinates')[1]}
          output_data.append(return_data)
      else:
          print(f"Error: {response.status_code}")

Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]

In [ ]:
output_data

[{'Long': -86.921641, 'Lat': 14.761664},
 {'Long': -86.921641, 'Lat': 14.761664}]

In [ ]:
output_df = pd.DataFrame(output_data)
output_df

        Long        Lat
0 -86.921641  14.761664
1 -86.921641  14.761664

In [ ]:
output_df.to_csv("Mapped_coordinates.csv", index = False)

In [ ]:
subset_df = df.iloc[:11000]
subset_df

,Index,Phylotype,Sub-Phylotype,Sequevar,Sub-sequevar designation,Strainname,Alt Names,"Environmental Source (Soil, Water, unknown plants)",Host Species (Common name),Host Species,...,Sequencing Tech,egl accession,mutS accession,other accession,Citation,Year published,Data entered by,Comments,Long,Lat
0,1,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Asclepias curassavica (Mexican Butterfly Weed),Asclepias curassavica,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641
1,2,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Cecropia peltata (Trumpet Tree),Cecropia peltata,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641
2,3,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Piper auritum (Mexican Pepperleaf),Piper auritum,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641
3,4,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Piper peltatum (Cordoncillo),Piper peltatum,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641
4,5,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Ricinus communis (Castor Bean),Ricinus communis,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641
5,6,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Solanum hirtum,Solanum hirtum,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641
6,7,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Solanum nigrum (Black Nightshade),Solanum nigrum,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641
7,8,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Solanum umbellatum (Borrachero),Solanum umbellatum,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641
8,9,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Solanum verbascifolium (Potato Tree),Solanum verbascifolium,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641
9,10,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Xanthosoma roseum (Elephant's Ear),Xanthosoma roseum,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641
10,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ageratum houstonianum (Bluemink),Ageratum houstonianum,...,NaN,NaN,NaN,NaN,"Pegg 1971, https://doi.org/10.1071/EA9710696",1971,Tiffany Lowe-Power,NaN,-22.572791,144.550390

In [ ]:
count = 0
lat = []
long = []

for index, row in subset_df.iterrows():
    if count > 11000:
        break
    params = {
        'q': row['Location Isolated'],
        'access_token': access_token
    }
    # Make the request
    response = requests.get(base_url, params=params)
    count += 1
    # Check if the request was successful
    if response.status_code == 200:
        # Parse the JSON response
        data = response.json()
        # Check if coordinates are present in the response
        if data.get('features'):
            coordinates = data.get('features')[0].get('geometry').get('coordinates')
            print(f"{row['Location Isolated']}'s coordinate are {coordinates}")
            lat.append(coordinates[0])
            long.append(coordinates[1])
        else:
            # Handle cases where coordinates are not found
            lat.append(None)  # or any suitable placeholder
            long.append(None)
            print(f"Coordinates not found for {row['Location Isolated']}")
    else:
        print(f"Error: {response.status_code}")
        # Append placeholders for failed requests to maintain length consistency
        lat.append(None)
        long.append(None)

# Now 'lat' and 'long' will have the same length as 'subset_df'
subset_df["Long"] = long
subset_df["Lat"] = lat
subset_df.head()

Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Honduras's coordinate are [-86.921641, 14.761664]
Queensland, Australia's coordinate are [144.55039, -22.572791]

,Index,Phylotype,Sub-Phylotype,Sequevar,Sub-sequevar designation,Strainname,Alt Names,"Environmental Source (Soil, Water, unknown plants)",Host Species (Common name),Host Species,...,Sequencing Tech,egl accession,mutS accession,other accession,Citation,Year published,Data entered by,Comments,Long,Lat
0,1,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Asclepias curassavica (Mexican Butterfly Weed),Asclepias curassavica,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641
1,2,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Cecropia peltata (Trumpet Tree),Cecropia peltata,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641
2,3,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Piper auritum (Mexican Pepperleaf),Piper auritum,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641
3,4,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Piper peltatum (Cordoncillo),Piper peltatum,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641
4,5,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Ricinus communis (Castor Bean),Ricinus communis,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,14.761664,-86.921641

In [ ]:
count = 0
lat = []
long = []

for index, row in subset_df.iterrows():
    if count > 11000:
        break

    location = row['Location Isolated']

    # Check if the location is empty
    if pd.isna(location) or location.strip() == "":
        lat.append(None)
        long.append(None)
        print(f"Skipped empty location at index {index}")
        continue  # Skip to the next iteration

    params = {
        'q': location,
        'access_token': access_token
    }

    # Make the request
    response = requests.get(base_url, params=params)
    count += 1

    # Check if the request was successful
    if response.status_code == 200:
        # Parse the JSON response
        data = response.json()
        # Check if coordinates are present in the response
        if data.get('features'):
            coordinates = data.get('features')[0].get('geometry').get('coordinates')
            print(f"{location}'s coordinates are {coordinates}")
            lat.append(coordinates[1])  # longitude is at index 0
            long.append(coordinates[0])  # latitude is at index 1
        else:
            # Handle cases where coordinates are not found
            lat.append(None)  # or any suitable placeholder
            long.append(None)
            print(f"Coordinates not found for {location}")
    else:
        print(f"Error: {response.status_code}")
        # Append placeholders for failed requests to maintain length consistency
        lat.append(None)
        long.append(None)

# Now 'lat' and 'long' will have the same length as 'subset_df'
subset_df["Long"] = long
subset_df["Lat"] = lat
subset_df.head()

Honduras's coordinates are [-86.921641, 14.761664]
Honduras's coordinates are [-86.921641, 14.761664]
Honduras's coordinates are [-86.921641, 14.761664]
Honduras's coordinates are [-86.921641, 14.761664]
Honduras's coordinates are [-86.921641, 14.761664]
Honduras's coordinates are [-86.921641, 14.761664]
Honduras's coordinates are [-86.921641, 14.761664]
Honduras's coordinates are [-86.921641, 14.761664]
Honduras's coordinates are [-86.921641, 14.761664]
Honduras's coordinates are [-86.921641, 14.761664]
Queensland, Australia's coordinates are [144.55039, -22.572791]

,Index,Phylotype,Sub-Phylotype,Sequevar,Sub-sequevar designation,Strainname,Alt Names,"Environmental Source (Soil, Water, unknown plants)",Host Species (Common name),Host Species,...,Sequencing Tech,egl accession,mutS accession,other accession,Citation,Year published,Data entered by,Comments,Long,Lat
0,1,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Asclepias curassavica (Mexican Butterfly Weed),Asclepias curassavica,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,-86.921641,14.761664
1,2,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Cecropia peltata (Trumpet Tree),Cecropia peltata,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,-86.921641,14.761664
2,3,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Piper auritum (Mexican Pepperleaf),Piper auritum,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,-86.921641,14.761664
3,4,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Piper peltatum (Cordoncillo),Piper peltatum,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,-86.921641,14.761664
4,5,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Ricinus communis (Castor Bean),Ricinus communis,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,-86.921641,14.761664

In [ ]:
len(lat)

11

In [ ]:
#Adding long and lat to dataset. They are switched because they were previously added in wrong order. Reverse this if geocode is fixed.
subset_df["Lat"] = long
subset_df["Long"] = lat
subset_df.head()

,Index,Phylotype,Sub-Phylotype,Sequevar,Sub-sequevar designation,Strainname,Alt Names,"Environmental Source (Soil, Water, unknown plants)",Host Species (Common name),Host Species,...,Sequencing Tech,egl accession,mutS accession,other accession,Citation,Year published,Data entered by,Comments,Long,Lat
0,1,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Asclepias curassavica (Mexican Butterfly Weed),Asclepias curassavica,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,-86.921641,14.761664
1,2,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Cecropia peltata (Trumpet Tree),Cecropia peltata,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,-86.921641,14.761664
2,3,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Piper auritum (Mexican Pepperleaf),Piper auritum,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,-86.921641,14.761664
3,4,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Piper peltatum (Cordoncillo),Piper peltatum,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,-86.921641,14.761664
4,5,NaN,NaN,NaN,"""SFR"" (Probably phyl. II, possibly sequevar 4)",NaN,NaN,NaN,Ricinus communis (Castor Bean),Ricinus communis,...,NaN,NaN,NaN,NaN,"Berg 1971, https://www.apsnet.org/publications...",1971,Tiffany Lowe-Power,NaN,-86.921641,14.761664

In [ ]:
coord_test = subset_df
subset_df.to_csv("RSSCCoordTestSmallGrabbed.csv", index = False) #Ben - This final cell will output a dataset with coordinate columns, ensure that you name it something you will remember.



```
# This is formatted as code
```
Testing the Coordinates

In [ ]:
continent_bounds = {
    "Africa": {
        "latitude": (-34.8, 37.5),
        "longitude": (-17.5, 65)
    },
    "Asia": {
        "latitude": (-10.0, 81.0),
        "longitude": (26.0, 180.0)
    },
    "Oceania": {
        "latitude": (-60.0, 10.0),
        "longitude": (112.0, 180.0)
    },
    "Europe": {
        "latitude": (36.0, 71.0),
        "longitude": (-25.0, 60.0)
    },
    "North America": {
        "latitude": (7.0, 83.0),
        "longitude": (-168.0, -13.0)
    },
    "South America": {
        "latitude": (-56.0, 12.0),
        "longitude": (-81.0, -35.0)
    }
}
continent_bounds["Asia"]
asia_longitude = continent_bounds["Asia"]["longitude"]
africa_longitude = continent_bounds["Africa"]["longitude"]
europe_longitude = continent_bounds["Europe"]["longitude"]
oceania_longitude = continent_bounds["Oceania"]["longitude"]
namerica_longitude = continent_bounds["North America"]["longitude"]
samerica_longitude = continent_bounds["South America"]["longitude"]
asia_longitude[0]

26.0

In [ ]:
# Add a new column 'Accuracy' that is based on a condition


# Set default value
coord_test['Long Accuracy'] = 'Inaccurate'

#'Asia'
coord_test.loc[
    (coord_test['Location (continent)'] == 'Asia') &
    coord_test['Long'].between(asia_longitude[0], asia_longitude[1]),
    'Long Accuracy'
] = 'Accurate'
#'North America'
coord_test.loc[
    (coord_test['Location (continent)'] == 'North America') &
    coord_test['Long'].between(namerica_longitude[0], namerica_longitude[1]),
    'Long Accuracy'
] = 'Accurate'

#'South America'
coord_test.loc[
    (coord_test['Location (continent)'] == 'South America') &
    coord_test['Long'].between(samerica_longitude[0], samerica_longitude[1]),
    'Long Accuracy'
] = 'Accurate'
#'Europe'
coord_test.loc[
    (coord_test['Location (continent)'] == 'Europe') &
    coord_test['Long'].between(europe_longitude[0], europe_longitude[1]),
    'Long Accuracy'
] = 'Accurate'
#Africa
coord_test.loc[
    (coord_test['Location (continent)'] == 'Africa') &
    coord_test['Long'].between(africa_longitude[0], africa_longitude[1]),
    'Long Accuracy'
] = 'Accurate'
#Oceania
coord_test.loc[
    (coord_test['Location (continent)'] == 'Oceania') &
    coord_test['Long'].between(oceania_longitude[0], oceania_longitude[1]),
    'Long Accuracy'
] = 'Accurate'

print(coord_test)

    Index  Phylotype  Sub-Phylotype  Sequevar  \
0       1        NaN            NaN       NaN
1       2        NaN            NaN       NaN
2       3        NaN            NaN       NaN
3       4        NaN            NaN       NaN
4       5        NaN            NaN       NaN
5       6        NaN            NaN       NaN
6       7        NaN            NaN       NaN
7       8        NaN            NaN       NaN
8       9        NaN            NaN       NaN
9      10        NaN            NaN       NaN
10     11        NaN            NaN       NaN

                          Sub-sequevar designation  Strainname  Alt Names  \
0   "SFR" (Probably phyl. II, possibly sequevar 4)         NaN        NaN
1   "SFR" (Probably phyl. II, possibly sequevar 4)         NaN        NaN
2   "SFR" (Probably phyl. II, possibly sequevar 4)         NaN        NaN
3   "SFR" (Probably phyl. II, possibly sequevar 4)         NaN        NaN
4   "SFR" (Probably phyl. II, possibly sequevar 4)         NaN        NaN
5   "SFR" (Probably phyl. II, possibly sequevar 4)         NaN        NaN
6   "SFR" (Probably phyl. II, possibly sequevar 4)         NaN        NaN
7   "SFR" (Probably phyl. II, possibly sequevar 4)         NaN        NaN
8   "SFR" (Probably phyl. II, possibly sequevar 4)         NaN        NaN
9   "SFR" (Probably phyl. II, possibly sequevar 4)         NaN        NaN
10                                             NaN         NaN        NaN

    Environmental Source (Soil, Water, unknown plants)  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN

                        Host Species (Common name)           Host Species   \
0   Asclepias curassavica (Mexican Butterfly Weed)   Asclepias curassavica
1                  Cecropia peltata (Trumpet Tree)        Cecropia peltata
2               Piper auritum (Mexican Pepperleaf)           Piper auritum
3                     Piper peltatum (Cordoncillo)          Piper peltatum
4                   Ricinus communis (Castor Bean)        Ricinus communis
5                                   Solanum hirtum          Solanum hirtum
6                Solanum nigrum (Black Nightshade)          Solanum nigrum
7                  Solanum umbellatum (Borrachero)      Solanum umbellatum
8             Solanum verbascifolium (Potato Tree)  Solanum verbascifolium
9               Xanthosoma roseum (Elephant's Ear)       Xanthosoma roseum
10                Ageratum houstonianum (Bluemink)   Ageratum houstonianum

    ... egl accession mutS accession other accession  \
0   ...           NaN            NaN             NaN
1   ...           NaN            NaN             NaN
2   ...           NaN            NaN             NaN
3   ...           NaN            NaN             NaN
4   ...           NaN            NaN             NaN
5   ...           NaN            NaN             NaN
6   ...           NaN            NaN             NaN
7   ...           NaN            NaN             NaN
8   ...           NaN            NaN             NaN
9   ...           NaN            NaN             NaN
10  ...           NaN            NaN             NaN

                                             Citation Year published  \
0   Berg 1971, https://www.apsnet.org/publications...           1971
1   Berg 1971, https://www.apsnet.org/publications...           1971
2   Berg 1971, https://www.apsnet.org/publications...           1971
3   Berg 1971, https://www.apsnet.org/publications...           1971
4   Berg 1971, https://www.apsnet.org/publications...           1971
5   Berg 1971, https://www.apsnet.org/publications...           1971
6   Berg 1971, https://www.apsnet.org/publications...           1971
7   Berg 1971, https://www.apsnet.org/publications...           1971
8   Berg 1971, https://www.apsnet.org/publications...           1971
9   Berg 1971, https://www.apsnet.org/publications...           1971
10       Pegg 1971, https://doi.org/10.1071/EA9710696           1971

       Data entered by Comments        Long        Lat  Long Accuracy
0   Tiffany Lowe-Power      NaN  -86.921641  14.761664       Accurate
1   Tiffany Lowe-Power      NaN  -86.921641  14.761664       Accurate
2   Tiffany Lowe-Power      NaN  -86.921641  14.761664       Accurate
3   Tiffany Lowe-Power      NaN  -86.921641  14.761664       Accurate
4   Tiffany Lowe-Power      NaN  -86.921641  14.761664       Accurate
5   Tiffany Lowe-Power      NaN  -86.921641  14.761664       Accurate
6   Tiffany Lowe-Power      NaN  -86.921641  14.761664       Accurate
7   Tiffany Lowe-Power      NaN  -86.921641  14.761664       Accurate
8   Tiffany Lowe-Power      NaN  -86.921641  14.761664       Accurate
9   Tiffany Lowe-Power      NaN  -86.921641  14.761664       Accurate
10  Tiffany Lowe-Power      NaN  144.550390 -22.572791       Accurate

[11 rows x 31 columns]